trigger:
- main

pool:
  name: 'Default'  
  demands:
  - agent.name -equals DESKTOP-7HI2KQN

steps:
- script: |
    python --version
  displayName: 'Set Up and Verify Local Python'

- script: |
    python main.py
  displayName: 'Run Python Script'

- script: |
    mkdir C:\IT
    copy output.txt C:\IT\
  displayName: 'Copy Artifacts to C:\\IT'

- script: |
    $versionStampFile = "C:\IT\txt.VersionStamp"
    $currentVersion = "1.0.0"
    $newVersion = [Version]::Parse($currentVersion).IncrementBuild()
    Set-Content $versionStampFile "$newVersion"
    echo "##vso[task.setvariable variable=versionNumber]$newVersion"
  displayName: 'Create Version Stamp'

- task: PowerShell@2
  displayName: 'Send Email Notification (Optional)'
  inputs:
    targetType: 'inline'
    script: |
      $to = "your_email@example.com"
      $from = "azure_devops@example.com"
      $subject = "Pipeline Run Status"
      $body = "Pipeline ran successfully. New version: $(versionNumber)"
      $smtpServer = "smtp.example.com"
      Send-MailMessage -To $to -From $from -Subject $subject -Body $body -SmtpServer $smtpServer
  condition: succeeded()
