trigger:
- main

pool:
  name: 'Default'  
  demands:
  - agent.name -equals DESKTOP-7HI2KQN

variables:
- group: EmailCredentials  # Link the variable group

steps:
- script: |
    python --version
  displayName: 'Set Up and Verify Local Python'

- script: |
    python main.py
  displayName: 'Run Python Script'

- script: |
    mkdir C:\IT
    copy output.txt C:\IT\
  displayName: 'Copy Artifacts to C:\\IT'

- task: PowerShell@2
  displayName: 'Create Version Stamp'
  inputs:
    targetType: inline
    script: |
      $versionStampFile = "C:\IT\VersionStamp.txt"
      $currentVersion = "1.0.0"

      # Split the version string into parts
      $versionParts = $currentVersion.Split('.')
      $versionParts[2] = [int]$versionParts[2] + 1  # Increment the last part
      $newVersion = "$($versionParts[0]).$($versionParts[1]).$($versionParts[2])"

      # Split the version into components (major.minor.patch) and increment the patch version
      # Example: For $currentVersion = "1.0.0":
      # $versionParts = $currentVersion.Split('.') => @("1", "0", "0")
      # $versionParts[2] = [int]$versionParts[2] + 1 increments the patch => @("1", "0", "1")
      # $newVersion = "$($versionParts[0]).$($versionParts[1]).$($versionParts[2])" reconstructs the version => "1.0.1"

      Set-Content -Path $versionStampFile -Value $newVersion
      Write-Host "Version stamp updated to: $newVersion"
      Write-Host "##vso[task.setvariable variable=versionNumber]$newVersion"

- task: PowerShell@2
  displayName: 'Send Email Notification (Optional)'
  inputs:
    targetType: inline
    script: |
      $to = "sam.albershtein@gmail.com"
      $from = "$(EmailUsername)"
      $subject = "Pipeline Run Status"
      $body = "Pipeline ran successfully. New version: $(versionNumber)"
      $smtpServer = "smtp.gmail.com"
      $smtpPort = 587
      $username = "$(EmailUsername)"
      $password = "$(EmailPassword)"
      $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
      $credential = New-Object System.Management.Automation.PSCredential($username, $securePassword)

      Send-MailMessage -To $to -From $from -Subject $subject -Body $body -SmtpServer $smtpServer -Port $smtpPort -UseSsl -Credential $credential
  condition: succeeded()

